### ISSUE TITLE
[1.19.2 Forge] Unable to apply all 3 enchantments

### ISSUE THREAD

**Issue by ANormalRaft** [Dplayend/Improved-Trident#1]
The mod's GIFs show all 3 trident enchantments applied on a trident, yet I am unable to enchant a trident with all those enchantments in survival

**Comment by Dplayend** [comment]
cuz you need [Merge Enchantments](https://legacy.curseforge.com/minecraft/mc-mods/merge-enchantments), sorry i didnt notice the description doesnt say anything about that, my bad
